apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: io.github.leryn.csi.s3driver
  namespace: kube-system
  labels: {}
  annotations: {}
spec:
  attachRequired: true
  # fsGroupPolicy: ReadWriteOnceWithFSType
  # podInfoOnMount: false
  # requiresRepublish: false
  # seLinuxMount: false
  storageCapacity: false
  # tokenRequests: []
  volumeLifecycleModes:
    - Persistent
    - Ephemeral