apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-nginx
  namespace: default
spec:
  serviceName: test-nginx
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-nginx
    spec:
      containers:
        - name: test-nginx
          image: nginx:1.22.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: webroot
        annotations:
          io.github.leryn.csi.s3driver/controller-publish-secret-name: "csi-s3driver-secret"
          io.github.leryn.csi.s3driver/node-stage-secret-name: "csi-s3driver-secret"
          io.github.leryn.csi.s3driver/node-publish-secret-name: "csi-s3driver-secret"
          io.github.leryn.csi.s3driver/controller-expand-secret-name: "csi-s3driver-secret"
      spec:
        storageClassName: csi-s3driver
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
