apiVersion: v1
kind: Pod
metadata:
  name: csi-s3driver-test-nginx
  namespace: default
spec:
  containers:
    - name: csi-s3driver-test-nginx
      image: nginx:1.22.1
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: webroot
  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: csi-s3driver-pvc
        readOnly: false
