---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: io.github.leryn.csi.s3driver
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver
    "app.kubernetes.io/component": csi-driver
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
