---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: csi-s3driver-sa
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-attacher-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": attacher-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-attacher-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-health-monitor-controller-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": health-monitor-controller-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-health-monitor-controller-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-provisioner-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": provisioner-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-provisioner-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-resizer-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": resizer-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-resizer-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-snapshotter-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": snapshotter-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-snapshotter-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-s3driver-attacher-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": attacher-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-attacher-cfg
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-s3driver-health-monitor-controller-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": health-monitor-controller-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-health-monitor-controller-cfg
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": provisioner-role
  name: csi-s3driver-provisioner-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-provisioner-cfg
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": resizer-role
  name: csi-s3driver-resizer-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-resizer-cfg
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-driver-s3fs
    "app.kubernetes.io/component": snapshotter-role
  name: csi-s3driver-snapshotter-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-snapshotter-leaderelection
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
