---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-s3driver-sa
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": serviceaccount
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-attacher-runner
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": attacher-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-attacher-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": attacher-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-attacher-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-provisioner-runner
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": provisioner-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-provisioner-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": provisioner-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-provisioner-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-resizer-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": resizer-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-resizer-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-snapshotter-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": snapshotter-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-snapshotter-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-s3driver-attacher-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": attacher-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-attacher-cfg
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-s3driver-provisioner-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": provisioner-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-provisioner-cfg
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3driver-health-monitor-controller-cluster-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": health-monitor-controller-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-health-monitor-controller-runner
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-s3driver-health-monitor-controller-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": health-monitor-controller-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-health-monitor-controller-cfg
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-s3driver-resizer-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": resizer-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-resizer-cfg
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-s3driver-snapshotter-role
  labels:
    "app.kubernetes.io/name": csi-s3driver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.s3driver
    "app.kubernetes.io/part-of": csi-s3driver-s3fs
    "app.kubernetes.io/component": snapshotter-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-snapshotter-leaderelection
subjects:
  - kind: ServiceAccount
    name: csi-s3driver-sa